### ISSUE TITLE
make APIs async

### ISSUE THREAD

**Issue by monaka** [RGB-Tools/rgb-lib#12]
This is a feature request. And related to #11.

There is `reqwest::blocking` module in the current version of `rgb-lib`.
That module uses tokio aync runtime.
 
It tends to be required to use async style in recent modern Rust programming.
I suppose that libraries should provide async runtime free APIs.

**Comment by monaka** [comment]
As #11 is resolved, this issue is not critical for me.
But I think async APIs will be required by many applications written in Rust. 
So I keep this open.

**Comment by nicbus** [comment]
rgb-lib APIs are currently blocking by choice, to avoid concurrent changes which could lead to issues. changing them to be async would require protecting big portions of the code so they're atomic, to prevent changes from concurrent calls, so it would not bring significant performance advantages

calling rgb-lib APIs from async code should work fine, now that #11 has been addressed, so we think it's best to keep APIs blocking for the time being

feel free to comment and re-open if needed
