### ISSUE TITLE
Can I use your public proxy server?

### ISSUE THREAD

**Issue by monaka** [RGB-Tools/rgb-lib#13]
This is not a bug report but a question.

I found an URL pointed to your proxy server in your  test code.
Should/Can I use your server?
Is it better to prepare my own proxy server instead ?

**Comment by nicbus** [comment]
> Should/Can I use your server?

feel free to use the public proxy server

> Is it better to prepare my own proxy server instead ?

in some cases, like local testing, it could be better to host your own. you can find the project [here](https://github.com/grunch/rgb-proxy-server), which is easy to run

**Comment by monaka** [comment]
Thank you for your answer and suggestion. I'll spawn my local server for testing.
