### ISSUE TITLE
Panicked in go_online()

### ISSUE THREAD

**Issue by monaka** [RGB-Tools/rgb-lib#15]
A unit test in my wallet is panicked in `_go_online()`.

Here is a message from the runtime.
```
thread '<unnamed>' panicked at 'running stored runtime: AppLevel(Database(Io(Custom { kind: Other, error: "could not acquire lock on \"/tmp/shiro-wallet/60ec7707/sled.db/db\": Os { code: 11, kind: WouldBlock, message: \"Resource temporarily unavailable\" }" })))', /home/monaka/.cargo/git/checkouts/rgb-lib-b21a551c0f942d1d/d1de142/src/wallet/mod.rs:1693:42
```

I found `/tmp/shiro-wallet/60ec7707/sled.db/db` on the test environment.

Referring to your code, the database is accessed in a other thread.

https://github.com/RGB-Tools/rgb-lib/blob/1028e9aff8e72fe79987a85bda9b2abfa5717883/src/wallet/mod.rs#L1693

I'm not sure but I suppose my unit tests are calling `go_online()` more than twice.
I think there is room to avoid or reduce panic.

However, I can fix it to reduce calling `go_online()` for now.
This is a feature request rather than a bug report.

**Comment by monaka** [comment]
I checked my code again and it may be caused by `stored`.

1. my modified code calls `go_online()` just once.
2. I got the same error reported above.

I asked about this issue on the `stored` repository.

**Comment by monaka** [comment]
I pushed code to reproduce this issue to https://github.com/diamondhands-dev/shiro-backend/tree/reproduction-rgb-lib-issue-15 .

3 failed test `test wallet::tests::test_put_bad`, `wallet::tests::test_put_failed`, 
 and `wallet::utxos::tests::test_get` have no `came here`|`came here!` in logs.
So they don't call `go_online()`.

The last test `wallet::utxos::tests::test_get` have `came here` in the log.
It is a first `go_online()` and it was panicked.

**Comment by nicbus** [comment]
calling `go_online()` more than once should work and is covered by tests

https://github.com/RGB-Tools/rgb-lib/blob/1028e9aff8e72fe79987a85bda9b2abfa5717883/src/wallet/test/go_online.rs#L16
the `success` test shows how to call `go_online()` twice successfully, using the same electrum and proxy URLs

https://github.com/RGB-Tools/rgb-lib/blob/1028e9aff8e72fe79987a85bda9b2abfa5717883/src/wallet/test/go_online.rs#L39
the `fail` test shows how `go_online()` returns a specific error (`CannotChangeOnline`) if called twice with mismatching URLs

it is not supposed to to panic so other issues might be at play

**Comment by monaka** [comment]
@nicbus @zoedberg Thank you for your comments.
As [I commented](https://github.com/RGB-Tools/rgb-lib/pull/16#issuecomment-1355908234), I see this issue is caused by my unexpected API calls.

I close this issue. And I raised #18 instead.
I suppose that #18 is an issue under expected calling steps.

I close this issue as `invalid`. Thank you for your help.

**Comment by zoedberg** [comment]
@monaka you're welcome. I've just seen #18 and I think I understand why it's failing. Shortly I will answer there too
