### ISSUE TITLE
Build fails on docs.rs

### ISSUE THREAD

**Issue by monaka** [RGB-Tools/rgb-lib#19]
![image](https://user-images.githubusercontent.com/101795/208285359-d9c65a7e-1157-440b-87e6-2c7c20f9edb7.png)

I fixed a similar issue on another crate before.
I'm going to make a pull request soon.

**Comment by monaka** [comment]
build logs on Docs.rs

<details>
<summary>Build #703328 2022-12-17T15:43:46.104041+00:00</summary>
---
# rustc version
rustc 1.68.0-nightly (9c07efe84 2022-12-16)
# docs.rs version
docsrs 0.6.0 (83e90006 2022-12-17)

# build log
[INFO] running `Command { std: "docker" "create" "-v" "/home/cratesfyi/workspace/builds/rgb-lib-0.1.4/target:/opt/rustwide/target:rw,Z" "-v" "/home/cratesfyi/workspace/builds/rgb-lib-0.1.4/source:/opt/rustwide/workdir:ro,Z" "-v" "/home/cratesfyi/workspace/cargo-home:/opt/rustwide/cargo-home:ro,Z" "-v" "/home/cratesfyi/workspace/rustup-home:/opt/rustwide/rustup-home:ro,Z" "-e" "SOURCE_DIR=/opt/rustwide/workdir" "-e" "CARGO_TARGET_DIR=/opt/rustwide/target" "-e" "DOCS_RS=1" "-e" "CARGO_HOME=/opt/rustwide/cargo-home" "-e" "RUSTUP_HOME=/opt/rustwide/rustup-home" "-w" "/opt/rustwide/workdir" "-m" "3221225472" "--cpus" "3" "--user" "1001:1001" "--network" "none" "ghcr.io/rust-lang/crates-build-env/linux@sha256:9db6adea6fe108e8475f2314ed6ea91319efc655499b550640da2809d69ffe6a" "/opt/rustwide/cargo-home/bin/cargo" "+nightly" "rustdoc" "--lib" "-Zrustdoc-map" "-Z" "unstable-options" "--config" "build.rustdocflags=[\"-Z\", \"unstable-options\", \"--emit=invocation-specific\", \"--resource-suffix\", \"-20221216-1.68.0-nightly-9c07efe84\", \"--static-root-path\", \"/-/rustdoc.static/\", \"--cap-lints\", \"warn\", \"--disable-per-crate-search\", \"--extern-html-root-takes-precedence\"]" "--offline" "-Zunstable-options" "--config=doc.extern-map.registries.crates-io=\"https://docs.rs/{pkg_name}/{version}/x86_64-unknown-linux-gnu\"" "-Zrustdoc-scrape-examples" "-j3" "--target" "x86_64-unknown-linux-gnu", kill_on_drop: false }`
[INFO] [stderr] WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
[INFO] [stdout] a401b28d8681592dfa3112c61cb087f460509a6bc2e24d4f2f17aaf7b49df9af
[INFO] running `Command { std: "docker" "start" "-a" "a401b28d8681592dfa3112c61cb087f460509a6bc2e24d4f2f17aaf7b49df9af", kill_on_drop: false }`
[INFO] [stderr]     Checking internet2 v0.8.4
[INFO] [stderr]    Compiling rgb_node v0.8.1
[INFO] [stderr] error: failed to run custom build command for `rgb_node v0.8.1`
[INFO] [stderr] 
[INFO] [stderr] Caused by:
[INFO] [stderr]   process didn't exit successfully: `/opt/rustwide/target/debug/build/rgb_node-31fcb5be2128ff27/build-script-build` (exit status: 1)
[INFO] [stderr]   --- stderr
[INFO] [stderr]   Error: I/O error: Read-only file system (os error 30)
[INFO] [stderr] warning: build failed, waiting for other jobs to finish...
[INFO] running `Command { std: "docker" "inspect" "a401b28d8681592dfa3112c61cb087f460509a6bc2e24d4f2f17aaf7b49df9af", kill_on_drop: false }`
[INFO] running `Command { std: "docker" "rm" "-f" "a401b28d8681592dfa3112c61cb087f460509a6bc2e24d4f2f17aaf7b49df9af", kill_on_drop: false }`
[INFO] [stdout] a401b28d8681592dfa3112c61cb087f460509a6bc2e24d4f2f17aaf7b49df9af
</details>

**Comment by monaka** [comment]
This issue will be fixed after RGB-WG/rgb-node#224 was fixed.

**Comment by zoedberg** [comment]
Also https://github.com/LNP-WG/lnp-core/pull/17 needs to be merged in order to fix this. Then we'll need to wait for new releases of rgb-node and lnp-core

**Comment by zoedberg** [comment]
Released a `0.1.5`, documentation build now succeeds so I'll close this as completed
