### ISSUE TITLE
Store scrypt parameters alongside encrypted backup

### ISSUE THREAD

**Issue by St333p** [RGB-Tools/rgb-lib#29]
The current backup codebase uses default parameters provided for scrypt to derive the backup encryption key from password. However, those parameters might change in the future, as they adapt to hardware advancements; this could prevent decryption of old backups due to differing key generation parameters.

Scrypt parameters should be stored in cleartext along with the salt, as they are also required to reconstruct the key deterministically, and thus decrypt the backup.

**Comment by zoedberg** [comment]
Solved in #30
