### ISSUE TITLE
rust-rgb20 build problems

### ISSUE THREAD

**Issue by bubbly-hb** [RGB-Tools/rgb-lib#33]
1. When I execute `git checkout v0.8.0-rc.3` , the dockerfile disappears. 
2. Based on 1, I execute `git checkout master` and `docker build -t rgb20:v0.8.0-rc.3 .`, but there is an error.
![buildrgb](https://github.com/RGB-Tools/rgb-lib/assets/55621732/315d4723-b5e9-4175-96df-43ce92578ee3)

**Comment by zoedberg** [comment]
It seems you've opened the issue on the wrong repository. I think you are referring to https://github.com/RGB-WG/rust-rgb20/tree/v0.8.0-rc.3. Moreover, please notice that the rust-rgb20 repository has been archived, you should look at https://github.com/RGB-WG/rgb and https://github.com/RGB-WG/rgb-schemata
