### ISSUE TITLE
about customized asset schema

### ISSUE THREAD

**Issue by cymqqqq** [RGB-Tools/rgb-lib#40]
Hi there, now there are three types of asset schemas in rgb-lib: nia, uda, and cfa. So if I want to add a new customized asset schema(let us denote it as rgb26), do I need to add it to the entity database first?

**Comment by dr-orlovsky** [comment]
RGBnn are not schemata, they are interface standards.

You can write as many new schema as you want, there is no need to register them anywhere or ask permission

**Comment by cymqqqq** [comment]
So can the interface standards be extended? Like the ERC721 and the ERC1155 standard.

**Comment by dr-orlovsky** [comment]
Yes, if the community decides so. But first, you need to put a rationale for that.

Are you sure you need an interface standard and not just a new schema under one of the existing standards?

Anyway, this repo has nothing to do with both questions; the proper place to discuss them is here: https://github.com/orgs/RGB-WG/discussions

**Comment by zoedberg** [comment]
Closing this because discussion moved to https://github.com/orgs/RGB-WG/discussions/62
