### ISSUE TITLE
compile rgb-lib with rgb-lightning-node error

### ISSUE THREAD

**Issue by cymqqqq** [RGB-Tools/rgb-lib#41]
Hi there, I git clone the latest code with uda, and compile it with the rgb-lightning-node, then the errors come out:
<img width="1253" alt="image" src="https://github.com/RGB-Tools/rgb-lib/assets/8555534/c8ca6ed3-730f-4ed1-96fd-89d30267af37">
So anyone know how to fix it?

**Comment by zoedberg** [comment]
Hi! I've pushed a new commit on the master branch of rgb-lightning-node (https://github.com/RGB-Tools/rgb-lightning-node/commit/b732f2a5714698551bbf65596cccd0c47f0a02dc) that fixes this issue (which is related to an old version of sea-orm, the library that rgb-lib uses to handle the DB)
