### ISSUE TITLE
about the database

### ISSUE THREAD

**Issue by cymqqqq** [RGB-Tools/rgb-lib#42]
I have a question about the entity database the rgb-lib chose in the source code, that is, why the sqlite is chosen here, but not the leveldb, or the rocksdb?

**Comment by cryptoquick** [comment]
SQLite is plenty performant compared to a specialized KV store. It's very fast. It's also nice to be able to perform relational queries if that's ever needed.

**Comment by zoedberg** [comment]
> why the sqlite is chosen here, but not the leveldb, or the rocksdb?

For the data we need to store in rgb-lib we think it's better to use a relational database. Moreover, in the future we plan to support more DB engines and to do that without writing too much code we've chosen to use an ORM. The ORM we've chosen is sea-orm, which currently supports SQLite, PostgreSQL and MySQL.
