### ISSUE TITLE
Since rgb is about to release version 0.11 beta6, will rgb-lib follow up?

### ISSUE THREAD

**Issue by eauxxs** [RGB-Tools/rgb-lib#48]
rgb-core is already 0.11 beta6, I think rgb and rgb-std should be soon. So I want to ask about the follow-up work of rgb-lib. As you know, beta6 refactored a lot of things, I think the workload should be a bit more.

**Comment by zoedberg** [comment]
Development of rgb-lib hasn't stopped, on the contrary we use its test suite to check and review every new PR on RGB libraries, so we're totally up to date with beta6 and we'll release a new version as soon as beta6 will be ready.
